# Usage:
# snakemake --profile profiles/slurm

use-conda: true
conda-frontend: mamba
printshellcmds: true
rerun-incomplete: true
keep-going: true
latency-wait: 120
restart-times: 1

jobs: 200

# Tell snakemake how to submit jobs
cluster: "sbatch --cpus-per-task={threads} --mem={resources.mem_mb}M --time={resources.runtime} --output=logs/slurm/%x-%j.out"

# Default resources for rules that don't set them
default-resources:
- mem_mb=8000
- runtime="04:00:00"
